import uuid
from typing import List
from datetime import datetime, timezone
from pydantic import BaseModel, Field


class ReportSection(BaseModel):
    """A specific section within a compliance report."""

    title: str = Field(description="Title of the section")
    content: str = Field(description="Markdown content of the section")
    citations: List[str] = Field(
        description="List of Foundry IQ citations used in this section"
    )

    @classmethod
    def example_data(cls) -> "ReportSection":
        return cls(
            title="Human Oversight Requirements",
            content="The system must implement human-in-the-loop mechanisms to prevent automated discrimination...",  # noqa: E501
            citations=["Article 14 - EU AI Act"],
        )


class ComplianceReport(BaseModel):
    """Comprehensive compliance report generated by the system."""

    report_id: uuid.UUID = Field(
        default_factory=uuid.uuid4, description="Unique report identifier"
    )
    system_name: str = Field(description="Name of the AI system analyzed")
    executive_summary: str = Field(
        description="High-level summary for board/legal stakeholders"
    )
    technical_findings: str = Field(
        description="Detailed technical breakdown for engineering"
    )
    certificate_draft: str = Field(
        description="Draft of formal compliance certificate"
    )  # noqa: E501
    sections: List[ReportSection] = Field(
        description="Detailed sections of the report"
    )  # noqa: E501
    risk_tier: str = Field(description="EU AI Act risk tier classification")
    compliance_percentage: float = Field(description="Overall compliance score")
    critical_gaps_count: int = Field(description="Number of critical gaps")
    generated_at: datetime = Field(description="When the report was generated")
    foundry_iq_citations_count: int = Field(
        description="Total number of citations used"
    )
    is_verified: bool = Field(
        description="Whether the report passed the verification agent"
    )
    verification_flags: List[str] = Field(
        description="List of flags raised by the verification agent"
    )

    @classmethod
    def example_data(cls) -> "ComplianceReport":
        return cls(
            system_name="TalentAI Pro",
            executive_summary="TalentAI Pro has been classified as High Risk. Significant gaps remain in human oversight...",  # noqa: E501
            technical_findings="Technical review indicates missing override hooks in the ranking algorithm...",  # noqa: E501
            certificate_draft="CERTIFICATE OF COMPLIANCE (DRAFT) - Pending remediation of critical gaps.",  # noqa: E501
            sections=[ReportSection.example_data()],
            risk_tier="HIGH RISK",
            compliance_percentage=47.5,
            critical_gaps_count=2,
            generated_at=datetime.now(timezone.utc),
            foundry_iq_citations_count=14,
            is_verified=True,
            verification_flags=[
                "Verification: Minor citation formatting fixed in section 2."
            ],
        )
